from __future__ import annotations

"""ORM models for the bilingual annotation assistant application."""
from app.db.session import Base

from datetime import datetime
from typing import Any

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text, JSON, UniqueConstraint, text
from sqlalchemy.orm import relationship, Mapped, mapped_column


class InputRecord(Base):
    """Represents the raw ingested input record from CSV or JSON input that needs to be annotated."""
    __tablename__ = "input_records"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    external_id: Mapped[str] = mapped_column(String(255), unique=True, index=True)
    source_text: Mapped[str] = mapped_column(Text, nullable=False)
    source_language: Mapped[str | None] = mapped_column(String(16), nullable=True, index=True)
    gold_label: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=text("CURRENT_TIMESTAMP"),
        nullable=False,
    )

    annotation_results: Mapped[list["AnnotationResult"]] = relationship(
        back_populates="input_record",
        cascade="all, delete-orphan",
    )

    review_queue_items: Mapped[list["ReviewQueueItem"]] = relationship(
        back_populates="input_record",
        cascade="all, delete-orphan",
    )


class AnnotationResult(Base):
    """Structured annotation result generated by the LLM pipeline for a given input record."""
    __tablename__ = "annotation_results"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    input_record_id: Mapped[int] = mapped_column(
        ForeignKey("input_records.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    source_language: Mapped[str | None] = mapped_column(String(16), nullable=True)
    issue_type: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    sentiment: Mapped[str | None] = mapped_column(String(32), nullable=True, index=True)
    urgency: Mapped[str | None] = mapped_column(String(32), nullable=True, index=True)
    summary_en: Mapped[str] = mapped_column(Text, nullable=False)
    summary_localized: Mapped[str] = mapped_column(Text, nullable=False)
    needs_human_review: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False, index=True)
    review_reason: Mapped[str | None] = mapped_column(String(128), nullable=True)
    prompt_version: Mapped[str | None] = mapped_column(String(32), nullable=True)
    model_name: Mapped[str | None] = mapped_column(String(128), nullable=True)
    raw_model_output: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=text("CURRENT_TIMESTAMP"),
        nullable=False,
    )

    input_record: Mapped["InputRecord"] = relationship(
        back_populates="annotation_results"
    )

    review_queue_items: Mapped[list["ReviewQueueItem"]] = relationship(
        back_populates="annotation_result",
        cascade="all, delete-orphan",
    )


class ReviewQueueItem(Base):
    """Queue item for human review of annotation results that are flagged as needing review."""
    __tablename__ = "review_queue_items"

    __table_args__ = (
        UniqueConstraint("annotation_result_id", "status", name="uq_review_queue_annotation_status"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    input_record_id: Mapped[int] = mapped_column(
        ForeignKey("input_records.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    annotation_result_id: Mapped[int | None] = mapped_column(
        ForeignKey("annotation_results.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    status: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    reason: Mapped[str] = mapped_column(String(128), nullable=False, index=True)
    reviewer_notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=text("CURRENT_TIMESTAMP"),
        nullable=False,
    )
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    input_record: Mapped["InputRecord"] = relationship(
        back_populates="review_queue_items"
    )

    annotation_result: Mapped[AnnotationResult | None] = relationship(
        back_populates="review_queue_items"
    )